[workspace]
members = ["remix", "mix-node"]
resolver = "2"

[profile.test]
opt-level = 1

[profile.release]
lto = true
codegen-units = 1
panic = "unwind"

# Speed up compile time checks for sqlx queries
[profile.dev.package.sqlx-macros]
opt-level = 3
# Cm8IuZ8tbGqRIhjR
