application:
  port: 0
  host: 0.0.0.0
  # auth token to access api, goes in header `Authorization: Bearer auth_token` of the request
  auth_token: ""
  # check on participants.json, it's easier to serialize
  participants: []
  # which participant the server was assigned by index in the vec
  # override by setting env APP_APPLICATION__WHOAMI=1
  whoami: 0
database:
  host: "127.0.0.1"
  port: 5432
  username: "username"
  password: "password"
  database_name: "iris-codes"
  require_ssl: false
